---
Name: amp
---
SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripers\AMP\Extensions\CMSMainExtension

SilverStripe\Control\Controller:
  extensions:
    - SilverStripers\AMP\Extensions\AMPControllerExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripers\AMP\Extensions\SiteTreeExtension
    - SilverStripers\AMP\Extensions\AMPMetaExtension

SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
          Middlewares:
            - '%$SilverStripers\AMP\Middleware\AMPMiddleware'
